export default [
	{
		// app设计
		"appImg" :[
			{
				price: 1,
				title: 'App首页设计',
				shop: '百度图片',
				type: 'APP设计',
				image: 'https://zhoukaiwen.com/img/Design/app/webapp.jpeg',
			},
			{
				price: 2,
				title: '「智慧社区」APP首页设计',
				shop: '项目UI设计',
				type: 'APP设计',
				image: 'https://zhoukaiwen.com/img/Design/app/sj_zhsq.jpeg',
			},
			{
				price: 3,
				title: '「插画风格」App设计',
				shop: 'UI设计达人',
				type: 'APP设计',
				image: 'https://zhoukaiwen.com/img/Design/app/sj_appch1.png',
			},
			{
				price: 4,
				title: '「插画风格」App设计',
				shop: 'UI设计达人',
				type: 'APP设计',
				image: 'https://zhoukaiwen.com/img/Design/app/sj_appch2.png',
			},
			{
				price: 6,
				title: '「商城类」App/移动端设计',
				shop: '项目UI设计',
				type: 'APP设计',
				image: 'https://zhoukaiwen.com/img/Design/app/sj_tyshop.png',
			},
			{
				price: 7,
				title: '移动端「签到」单页面设计',
				shop: '项目UI设计',
				type: 'APP设计',
				image: 'https://zhoukaiwen.com/img/Design/app/psketch.png',
			},
			{
				price: 8,
				title: '移动端「咨询」单页面设计',
				shop: '项目UI设计',
				type: 'APP设计',
				image: 'https://zhoukaiwen.com/img/Design/app/sj_zx.jpeg',
			},
			{
				price: 9,
				title: '移动端「实名认证1」单页面设计',
				shop: '项目UI设计',
				type: 'APP设计',
				image: 'https://zhoukaiwen.com/img/Design/app/sj_smrz.jpeg',
			},
			{
				price: 10,
				title: '移动端「排行榜」单页面设计',
				shop: '项目UI设计',
				type: 'APP设计',
				image: 'https://zhoukaiwen.com/img/Design/app/sj_appphb1.jpeg',
			},
			{
				price: 11,
				title: '「电商」App页面设计',
				shop: '项目UI设计',
				type: 'APP设计',
				image: 'https://zhoukaiwen.com/img/Design/app/sj_appshop.jpeg',
			},
			{
				price: 12,
				title: '「课程」App页面设计',
				shop: '项目UI设计',
				type: 'APP设计',
				image: 'https://zhoukaiwen.com/img/Design/app/1psketch.png',
			},
			{
				price: 13,
				title: '「弹窗」App页面设计',
				shop: '项目UI设计',
				type: 'APP设计',
				image: 'https://zhoukaiwen.com/img/Design/app/2psketch.png',
			},
			{
				price: 14,
				title: '「排行榜」App页面设计',
				shop: '项目UI设计',
				type: 'APP设计',
				image: 'https://zhoukaiwen.com/img/Design/app/3psketch.png',
			},
			{
				price: 15,
				title: '「国外」App页面设计',
				shop: '项目UI设计',
				type: 'APP设计',
				image: 'https://zhoukaiwen.com/img/Design/app/4psketch.png',
			},
			{
				price: 16,
				title: '「聊天」App页面设计-1',
				shop: '项目UI设计',
				type: 'APP设计',
				image: 'https://zhoukaiwen.com/img/Design/app/5psketch.png',
			}
		],
		// pc端设计
		"pcImg" :[
			{
				price: 1,
				title: '「一标三实」后台管理系统',
				shop: '项目UI设计',
				type: 'PC设计',
				image: 'https://zhoukaiwen.com/img/Design/pc/ybss_jt.png',
			},
			{
				price: 2,
				title: '智慧社区大数据沙盘',
				shop: '项目UI设计',
				type: 'PC设计',
				image: 'https://zhoukaiwen.com/img/Design/pc/sj_zhsqsp.jpeg',
			}
		],
		// logo设计
		"logoImg" :[
			{
				price: 1,
				title: '科技Logo',
				shop: '百度图片',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/logo.jpeg',
			},
			{
				price: 2,
				title: '设计Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/logo.png',
			},
			{
				price: 3,
				title: '设计Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch1.png',
			},
			{
				price: 4,
				title: '大麦Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch2.png',
			},
			{
				price: 5,
				title: '某学Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch3.png',
			},
			{
				price: 6,
				title: '猫头鹰Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch4.png',
			},
			{
				price: 7,
				title: 'Expedia Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch5.png',
			},
			{
				price: 8,
				title: 'Ant Design Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch6.png',
			},
			{
				price: 9,
				title: '视觉设计Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch7.png',
			},
			{
				price: 10,
				title: '高德Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch8.png',
			},
			{
				price: 11,
				title: '饿了么Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch9.png',
			},
			{
				price: 12,
				title: '顺丰Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch10.png',
			},
			{
				price: 13,
				title: '阿里妈妈Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch11.png',
			},
			{
				price: 14,
				title: '咸鱼Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch12.png',
			},
			{
				price: 15,
				title: '万能钥匙Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch13.png',
			},
			{
				price: 16,
				title: '设计Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch14.png',
			},
			{
				price: 17,
				title: '赶集网Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch15.png',
			},
			{
				price: 18,
				title: '蜜淘网Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch16.png',
			},
			{
				price: 19,
				title: '蘑菇街Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch17.png',
			},
			{
				price: 20,
				title: '腾讯视频Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch18.png',
			},
			{
				price: 21,
				title: '腾讯新闻Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch19.png',
			},
			{
				price: 22,
				title: '聚划算Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch20.png',
			},
			{
				price: 23,
				title: '百度翻译Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch21.png',
			},
			{
				price: 24,
				title: '有道翻译Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch22.png',
			},
			{
				price: 25,
				title: '开课吧Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch23.png',
			},
			{
				price: 26,
				title: '百度搜索Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch24.png',
			},
			{
				price: 27,
				title: '知乎Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch25.png',
			},
			{
				price: 28,
				title: '百度贴吧Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch26.png',
			},
			{
				price: 29,
				title: '热气球Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch27.png',
			},
			{
				price: 30,
				title: '百度云盘Logo',
				shop: 'Kevin设计',
				type: 'Logo设计',
				image: 'https://zhoukaiwen.com/img/Design/logo/psketch28.png',
			}
		],
		// 海报设计
		"posterImg" :[
			{
				price: 1,
				title: '「宅家学IT」海报设计',
				shop: 'Kevin同学',
				type: '海报设计',
				image: 'https://zhoukaiwen.com/img/Design/poster/zjx_hb.png',
			},
			{
				price: 2,
				title: '「社区招募」海报设计',
				shop: '项目UI设计',
				type: '海报设计',
				image: 'https://zhoukaiwen.com/img/Design/poster/sj_zm.jpeg',
			},
			{
				price: 3,
				title: '动漫风「海报背景图1」设计',
				shop: '项目UI设计',
				type: '海报设计',
				image: 'https://zhoukaiwen.com/img/Design/poster/sj_hbbg1.jpeg',
			},
			{
				price: 4,
				title: '动漫风「海报背景图2」设计',
				shop: '项目UI设计',
				type: '海报设计',
				image: 'https://zhoukaiwen.com/img/Design/poster/sj_hbbg2.jpeg',
			},
			{
				price: 5,
				title: '动漫风「海报背景图3」设计',
				shop: '项目UI设计',
				type: '海报设计',
				image: 'https://zhoukaiwen.com/img/Design/poster/sj_hbbg3.jpeg',
			},
			{
				price: 6,
				title: '「海报背景图3」设计',
				shop: '项目UI设计',
				type: '海报设计',
				image: 'https://zhoukaiwen.com/img/Design/poster/p1.jpeg',
			},
			{
				price: 7,
				title: '「海报背景图3」设计',
				shop: '项目UI设计',
				type: '海报设计',
				image: 'https://zhoukaiwen.com/img/Design/poster/p2.jpeg',
			},
			{
				price: 8,
				title: '「海报背景图3」设计',
				shop: '项目UI设计',
				type: '海报设计',
				image: 'https://zhoukaiwen.com/img/Design/poster/p3.jpeg',
			}
		]
	}
]
